# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: fe24klassen
# "service" is the name of this project. This will also be added to your AWS resource names.
service: backend

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role: arn:aws:iam::102503112251:role/lecture-role
  httpApi:
    cors:
      allowedOrigins:
        - 'http://localhost:5173'
        - 'http://shui-frontend-john2025.s3-website.eu-north-1.amazonaws.com'
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE      

functions:
  postMessage:
    handler: functions/postMessage/index.handler
    events:
      - httpApi:
          path: /create
          method: post

  updateMessage:
    handler: functions/updateMessage/index.handler
    events:
      - httpApi:
          path: /update/{id}
          method: put

  getMessages:
    handler: functions/getMessages/index.handler
    events:
      - httpApi:
          path: /messages
          method: get

  deleteMessages:
    handler: functions/deleteMessage/index.handler
    events:
      - httpApi:
          path: /delete/{id}
          method: delete

  getMessageByUser:
    handler: functions/getMessagebyUser/index.handler
    events:
      - httpApi:
          path: /messages/{username}
          method: get

resources:
  Resources:
    ShuiMessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ShuiMessagesTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: usernameIndex
            KeySchema:
              - AttributeName: username
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST